print("Welcome to the Hotel De Luna.")
print("\nDo you want a room reservation? Type 1 if Yes and 2 for No: ", end ="")
reserv = input()
if reserv == "1":
    print("Here's our list for rooms")
    print("1 = Deluxe Room ")
    print("2 = Double-Double (Twin Double) Room")
    print("3 = Twin Room")
    print("May I know what room you prefer?: ", end ="")
    pref = input()
    
    if pref == "1":
        print("Great! Deluxe Room will be $500. And would you prefer to have a room with a view of the ocean?(1 for YES and 2 for NO): ", end ="")
        oc = input()
        if oc == 1:
            print("Great! That will add $20")
            print("\nMay I know what is the exact date of your arrival?: ", end ="")
            date = input()
            print("Okay. For how many nights will you be staying?: ", end ="")
            night = input()
            print("Great! For how many people is the reservation for?: ", end ="")
            people = input()
            print("Can we know the name?: ", end ="")
            name = input()
            print("Thank you for answering. May I know your number?: ", end ="")
            num = input()
            print("Okay " + name + " your reservation is to " + date + " for " + str(people) + " person. Thank you for choosing Hotel De Luna. Have a nice day!", end ="")
        else :
            print("Great! That will add $20", end ="")
            print("May I know what is the exact date of your arrival?: ", end ="")
            date = input()
            print("Okay. For how many nights will you be staying?: ", end ="")
            night = input()
            print("Great! For how many people is the reservation for?: ", end ="")
            people = input()
            print("Can we know the name?: ", end ="")
            name = input()
            print("Thank you for answering. May I know your number?: ", end ="")
            num = input()
            print("Okay " + name + " your reservation is to " + date + " for " + str(people) + " person. Thank you for choosing Hotel De Luna. Have a nice day!", end ="")
    elif(pref == 1) :
        print("Great! Deluxe Room will be $500. And would you prefer to have a room with a view of the ocean?(1 for YES and 2 for NO): ", end ="")
        oc = input()
        if oc == 1 :
            print("Great! That will add $20")
            print("May I know what is the exact date of your arrival?: ", end ="")
            date = input()
            print("Okay. For how many nights will you be staying?: ", end ="")
            night = input()
            print("Great! For how many people is the reservation for?: ", end ="")
            people = input()
            print("Can we know the name?: ", end ="")
            name = input()
            print("Thank you for answering. May I know your number?: ", end ="")
            num = input()
            print("Okay " + name + " your reservation is to " + date + " for " + str(people) + " person. Thank you for choosing Hotel De Luna. Have a nice day!", end ="")
        else :
            print("Great! That will add $20", end ="")
            print("May I know what is the exact date of your arrival?: ", end ="")
            date = input()
            print("Okay. For how many nights will you be staying?: ", end ="")
            night = input()
            print("Great! For how many people is the reservation for?: ", end ="")
            people = input()
            print("Can we know the name?: ", end ="")
            name = input()
            print("Thank you for answering. May I know your number?: ", end ="")
            num = input()
            print("Okay " + name + " your reservation is to " + date + " for " + str(people) + " person. Thank you for choosing Hotel De Luna. Have a nice day!", end ="")
    else :
        print("Great! Deluxe Room will be $500. And would you prefer to have a room with a view of the ocean?(1 for YES and 2 for NO): ", end ="")
        oc = input()
        if (oc == 1) :
            print("Great! That will add $20")
            print("May I know what is the exact date of your arrival?: ", end ="")
            date = input()
            print("Okay. For how many nights will you be staying?: ", end ="")
            night = input()
            print("Great! For how many people is the reservation for?: ", end ="")
            people = input()
            print("Can we know the name?: ", end ="")
            name = input()
            print("Thank you for answering. May I know your number?: ", end ="")
            num = input()
            print("Okay " + name + " your reservation is to " + date + " for " + str(people) + " person. Thank you for choosing Hotel De Luna. Have a nice day!", end ="")
        else :
            print("Great! That will add $20", end ="")
            print("May I know what is the exact date of your arrival?: ", end ="")
            date = input()
            print("Okay. For how many nights will you be staying?: ", end ="")
            night = input()
            print("Great! For how many people is the reservation for?: ", end ="")
            people = input()
            print("Can we know the name?: ", end ="")
            name = input()
            print("Thank you for answering. May I know your number?: ", end ="")
            num = input()
            print("Okay " + name + " your reservation is to " + date + " for " + str(people) + " person. Thank you for choosing Hotel De Luna. Have a nice day!", end ="")
else :
    print("\nThank you for contacting Hotel De Luna ", end ="")